import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { CircleDollarSign, RefreshCw, UsersRound } from "lucide-react";
import { api, currentUser } from "../api";
import { EmptyState, PageHeader, StatusBadge } from "../components/common";

type Compensation = { id: string; caseId: string; caseReference: string; parcelId: string; village: string; assessedAmount: number; approvedAmount: number; paidAmount: number; status: string; paymentReference?: string };
type RR = { id: string; caseId: string; caseReference: string; parcelId: string; village: string; affectedFamilies: number; displacedFamilies: number; eligibleFamilies: number; benefitsDelivered: number; status: string };
const money = (value: number) => `₹${value.toLocaleString("en-IN")}`;
const canUpdate = () => ["SUPER_ADMIN", "NATIONAL_ADMIN", "DEPARTMENT_ADMIN", "PROJECT_OFFICER", "DISTRICT_OFFICER"].includes(currentUser()?.role || "");

function LoadError({ error, retry }: { error: string; retry: () => void }) { return <section className="panel empty-state"><span>{error}</span><button className="button button-secondary button-sm" onClick={retry}>Try again</button></section>; }
function Metric({ label, value }: { label: string; value: string }) { return <div className="stat-card"><div className="stat-icon blue"><CircleDollarSign size={19} /></div><div className="stat-label">{label}</div><strong className="stat-value">{value}</strong><span className="stat-delta">Persistent case data</span></div>; }

export function CompensationPage() {
  const [rows, setRows] = useState<Compensation[]>([]), [busy, setBusy] = useState(""), [message, setMessage] = useState(""), [error, setError] = useState(""), [loaded, setLoaded] = useState(false);
  const refresh = async () => { setError(""); try { setRows(await api<Compensation[]>("/compensation")); } catch (err) { setError(err instanceof Error ? err.message : "Compensation records could not be loaded."); } finally { setLoaded(true); } };
  useEffect(() => { refresh(); }, []);
  const totals = useMemo(() => rows.reduce((sum, row) => ({ assessed: sum.assessed + row.assessedAmount, approved: sum.approved + row.approvedAmount, paid: sum.paid + row.paidAmount }), { assessed: 0, approved: 0, paid: 0 }), [rows]);
  async function update(row: Compensation) { setBusy(row.id); try { await api(`/compensation/${row.id}`, { method: "PATCH", body: JSON.stringify({ status: "APPROVED", approvedAmount: row.assessedAmount }) }); setMessage(`${row.caseReference} approved. The owner and assigned officer were notified.`); await refresh(); } catch (err) { setMessage(err instanceof Error ? err.message : "Update failed."); } finally { setBusy(""); } }
  async function sync(row: Compensation) { setBusy(row.id); try { const result = await api<Compensation>(`/compensation/${row.id}/sync`, { method: "POST" }); setMessage(`PFMS DEMO sync returned ${result.status.replaceAll("_", " ")} for ${row.caseReference}${result.paymentReference ? ` · ${result.paymentReference}` : ""}.`); await refresh(); } catch (err) { setMessage(err instanceof Error ? err.message : "PFMS synchronization failed."); } finally { setBusy(""); } }
  return <><PageHeader title="Compensation monitoring" description="Case-level assessment, approval, payment, and clearly labelled PFMS DEMO reconciliation." />{message && <div className="login-note">{message}</div>}<div className="stat-grid"><Metric label="Assessed" value={money(totals.assessed)} /><Metric label="Approved" value={money(totals.approved)} /><Metric label="Paid" value={money(totals.paid)} /><Metric label="Payment pending" value={String(rows.filter((r) => r.status !== "PAID").length)} /></div>{!loaded ? <section className="panel empty-state">Loading compensation records…</section> : error ? <LoadError error={error} retry={refresh} /> : <section className="panel table-panel"><div className="table-top">{rows.length} role-visible compensation records <small>· PFMS IS DEMO / MOCK</small></div>{rows.length ? <div className="table-scroll"><table><thead><tr><th>Case / parcel</th><th>Assessed</th><th>Approved</th><th>Paid</th><th>Payment</th><th>Status</th><th>Action</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td><Link className="table-title" to={`/cases/${row.caseId}`}>{row.caseReference}<span className="table-sub">{row.parcelId} · {row.village}</span></Link></td><td>{money(row.assessedAmount)}</td><td>{money(row.approvedAmount)}</td><td>{money(row.paidAmount)}</td><td>{row.paymentReference || "Awaiting PFMS DEMO sync"}</td><td><StatusBadge status={row.status} /></td><td>{canUpdate() && <div className="detail-actions">{row.status === "ASSESSED" && <button disabled={!!busy} className="button button-secondary button-sm" onClick={() => update(row)}>Approve</button>}{row.status !== "PAID" && <button disabled={!!busy} className="button button-primary button-sm" onClick={() => sync(row)}><RefreshCw size={13} />{busy === row.id ? "Syncing…" : "PFMS DEMO sync"}</button>}</div>}</td></tr>)}</tbody></table></div> : <EmptyState text="No compensation records are assigned to this role." />}</section>}</>;
}

export function RRPage() {
  const [rows, setRows] = useState<RR[]>([]), [message, setMessage] = useState(""), [error, setError] = useState(""), [loaded, setLoaded] = useState(false), [busy, setBusy] = useState("");
  const refresh = async () => { setError(""); try { setRows(await api<RR[]>("/rr")); } catch (err) { setError(err instanceof Error ? err.message : "R&R records could not be loaded."); } finally { setLoaded(true); } };
  useEffect(() => { refresh(); }, []);
  async function update(row: RR) { setBusy(row.id); try { await api(`/rr/${row.id}`, { method: "PATCH", body: JSON.stringify({ status: "COMPLETED", benefitsDelivered: row.eligibleFamilies }) }); setMessage(`${row.caseReference} R&R completion recorded; the responsible officer was notified.`); await refresh(); } catch (err) { setMessage(err instanceof Error ? err.message : "R&R update failed."); } finally { setBusy(""); } }
  return <><PageHeader title="Rehabilitation & resettlement" description="Affected-family benefit tracking tied to the same acquisition cases." />{message && <div className="login-note">{message}</div>}<div className="stat-grid"><Metric label="Affected families" value={String(rows.reduce((sum, row) => sum + row.affectedFamilies, 0))} /><Metric label="Eligible families" value={String(rows.reduce((sum, row) => sum + row.eligibleFamilies, 0))} /><Metric label="Benefits delivered" value={String(rows.reduce((sum, row) => sum + row.benefitsDelivered, 0))} /><Metric label="Completion pending" value={String(rows.filter((row) => row.status !== "COMPLETED").length)} /></div>{!loaded ? <section className="panel empty-state">Loading R&R records…</section> : error ? <LoadError error={error} retry={refresh} /> : <section className="panel table-panel"><div className="table-top">{rows.length} role-visible R&R records linked to acquisition cases</div>{rows.length ? <div className="table-scroll"><table><thead><tr><th>Case / parcel</th><th>Affected</th><th>Displaced</th><th>Eligible</th><th>Benefits delivered</th><th>Status</th><th>Action</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td><Link className="table-title" to={`/cases/${row.caseId}`}>{row.caseReference}<span className="table-sub">{row.parcelId} · {row.village}</span></Link></td><td>{row.affectedFamilies}</td><td>{row.displacedFamilies}</td><td>{row.eligibleFamilies}</td><td>{row.benefitsDelivered} / {row.eligibleFamilies}</td><td><StatusBadge status={row.status} /></td><td>{canUpdate() && row.status !== "COMPLETED" && <button disabled={!!busy} className="button button-primary button-sm" onClick={() => update(row)}><UsersRound size={13} />{busy === row.id ? "Updating…" : "Mark completed"}</button>}</td></tr>)}</tbody></table></div> : <EmptyState text="No R&R records are assigned to this role." />}</section>}</>;
}
